---
name: File-Stat-Moose
version: 0.0105
author:
  - 'Piotr Roszatycki <dexter@debian.org>'
abstract: 'Status info for a file - Moose-based'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exception::Base: 0.14
  Exception::System: 0.0801
  Moose: 0
  perl: 5.006
build_requires:
  Test::Unit::Lite: 0.07
provides:
  File::Stat::Moose:
    file: lib/File/Stat/Moose.pm
    version: 0.0105
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
