---
name: File-Stat-Moose
version: 0.05
author:
  - 'Piotr Roszatycki <dexter@cpan.org>'
abstract: 'Status info for a file - Moose-based'
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-Stat-Moose
  license: http://dev.perl.org/licenses/
  repository: http://code2.0beta.co.uk/moose/svn/File-Stat-Moose
requires:
  DateTime: 0
  Exception::Argument: 0.05
  Exception::Base: 0.21
  Exception::System: 0.11
  Moose: 0
  Sub::Exporter: 0
  Test::Assert: 0.04
  constant::boolean: 0
  perl: 5.008
build_requires:
  Exception::Died: 0.04
  Exception::Warning: 0.03
  Test::Unit::Lite: 0.11
  parent: 0
provides:
  Exception::IO:
    file: lib/Exception/IO.pm
    version: 0.05
  File::Stat::Moose:
    file: lib/File/Stat/Moose.pm
    version: 0.05
  MooseX::Types::CacheFileHandle:
    file: lib/MooseX/Types/CacheFileHandle.pm
    version: 0.05
  MooseX::Types::OpenHandle:
    file: lib/MooseX/Types/OpenHandle.pm
    version: 0.05
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
